title: 'The Point of Sale  Systems that will  Revolutionize  Your Business FOR FREE!'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.03476128540933132
  lightness: 0.3163279274012893
  brandStrength: 0.506383
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#878A8F'
    - '#005778'
    - '#9B1410'
  rhythmicContrast: 0.2489338251762092
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: HarbortouchSA.com
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8468085
layout_spectrum: 0.5212766
