name: HarbortouchSA.com
favicon: null
layout_spectrum: 0.65006
typography_spectrum: 0.63392
title: 'The Point of Sale  Systems that will  Revolutionize  Your Business FOR FREE!'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#afafaf'
    - '#009dd0'
    - '#00618e'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.5297872
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
