name: HarbortouchSA.com
favicon: null
layout_spectrum: 0.3988183618057519
typography_spectrum: 0.5097746825776994
title: 'The Point of Sale  Systems that will  Revolutionize  Your Business FOR FREE!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.05846014944836497
  lightness: 0.31632792740128934
  saturation: 0.03476128540933132
  rhythmicContrast: 0.2489338251762092
purpose: []
