layout_spectrum: 0.4562432795403396
typography_spectrum: 0.28464948851357
color:
  brandColors:
    - '#000000'
    - '#afafaf'
    - '#009dd0'
    - '#00618e'
    - '#ffffff'
  brandStrength: 0.7733533844617334
  lightness: 0.6890540853458098
  saturation: 0.8884862454314855
  rhythmicContrast: 0.778816478015523
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: harbortouchsa
analytics:
  google: null
  facebook: null
  twitter: Harbortouch
author:
  name: Harbortouch of San Antonio
  email: ddikin@harbortouchsa.com
  url: 'https://www.harbortouchsa.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ead2bdb-c49c-4aae-b803-37432fbd2464.png
name: Harbortouchsa.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Harbortouch Hospitality
    id: fa4314f4-9bb5-4d50-995a-29afd3ed2f5f
    type: content
  - name: Harbortouch Echo
    id: 8db4de52-3884-4ac1-8af0-0ff97782b429
    type: content
  - name: Countertop Units
    id: c43ba335-73d1-4ed6-b5b9-63e7ee8bcb73
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ccd5637e-3fff-490f-af8c-2d86ee64f4cc.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Point of Sale  Systems that will  Revolutionize  Your Business...
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a333f68b-7cdb-4b95-bfa4-2395cdd43ff5.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a333f68b-7cdb-4b95-bfa4-2395cdd43ff5.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:info@harbortouchsa.com'
    label: Email us
  - type: contact
    url: 'tel:8007965384'
    label: 'Toll Free: 800-796-5384'
